# Generated by Django 3.2.12 on 2022-04-27 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_alter_user_user_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False, verbose_name='file ID')),
                ('file_name', models.CharField(max_length=20)),
                ('file_extension', models.CharField(max_length=5)),
                ('file_path', models.CharField(max_length=512)),
            ],
            options={
                'db_table': 'file',
            },
        ),
        migrations.CreateModel(
            name='Minutes',
            fields=[
                ('mn_id', models.AutoField(primary_key=True, serialize=False, verbose_name='minute ID')),
                ('mn_make_date', models.DateTimeField(auto_now_add=True)),
                ('mn_title', models.CharField(max_length=50)),
                ('mn_date', models.DateField(null=True)),
                ('mn_place', models.CharField(max_length=20, null=True)),
                ('mn_explanation', models.CharField(max_length=50, null=True)),
                ('mn_memo', models.CharField(max_length=500, null=True)),
                ('mn_share_link', models.CharField(max_length=512, null=True)),
                ('dr_id', models.ForeignKey(db_column='dr_id', on_delete=django.db.models.deletion.CASCADE, related_name='minutes', to='user.directory')),
                ('file_id', models.ForeignKey(db_column='file_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minutes', to='minute.file')),
            ],
            options={
                'db_table': 'minutes',
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('speaker_seq', models.AutoField(primary_key=True, serialize=False, verbose_name="speaker's ID")),
                ('speaker_name', models.CharField(max_length=20, null=True)),
                ('mn_id', models.ForeignKey(db_column='mn_id', on_delete=django.db.models.deletion.CASCADE, related_name='speaker', to='minute.minutes')),
            ],
            options={
                'db_table': 'speaker',
            },
        ),
        migrations.AddField(
            model_name='minutes',
            name='speaker_seq',
            field=models.ForeignKey(db_column='speaker_seq', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minutes', to='minute.speaker'),
        ),
        migrations.AddField(
            model_name='minutes',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='minutes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('bm_seq', models.AutoField(primary_key=True, serialize=False, verbose_name='bookmark ID')),
                ('bm_start', models.CharField(max_length=10)),
                ('bm_end', models.CharField(max_length=10)),
                ('bm_name', models.CharField(max_length=20)),
                ('mn_id', models.ForeignKey(db_column='mn_id', on_delete=django.db.models.deletion.CASCADE, related_name='bookmark', to='minute.minutes')),
            ],
            options={
                'db_table': 'bookmark',
            },
        ),
    ]
