# Generated by Django 3.2.12 on 2022-05-07 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('minute', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('mn_id', models.ForeignKey(db_column='dr_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='summarys', serialize=False, to='minute.minutes', unique=True)),
                ('summary', models.TextField(blank=True, default='', verbose_name="minute's summary")),
            ],
            options={
                'db_table': 'summary',
            },
        ),
    ]
