# Generated by Django 3.2.12 on 2022-05-07 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('minute', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceRecognition',
            fields=[
                ('vr_id', models.AutoField(primary_key=True, serialize=False, verbose_name='voice recognition id')),
                ('vr_seq', models.IntegerField()),
                ('vr_start', models.CharField(max_length=14)),
                ('vr_end', models.CharField(max_length=14)),
                ('vr_text', models.CharField(max_length=1000)),
                ('mn_id', models.ForeignKey(db_column='mn_id', on_delete=django.db.models.deletion.CASCADE, related_name='voice_recognition', to='minute.minutes')),
                ('speaker_seq', models.ForeignKey(db_column='speaker_seq', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_recognition', to='minute.speaker')),
            ],
            options={
                'db_table': 'voice_recognition',
            },
        ),
    ]
