# Generated by Django 3.2.12 on 2022-05-16 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_recognition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicerecognition',
            name='emotion_type',
            field=models.IntegerField(default=4),
        ),
    ]
