# Generated by Django 3.2.12 on 2022-04-05 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name="user's email")),
                ('user_profile', models.ImageField(blank=True, null=True, upload_to='image/profile/', verbose_name="user's profile path")),
                ('username', models.CharField(default='', max_length=20, unique=True, verbose_name="user's name")),
                ('user_sign_up_date', models.DateTimeField(auto_now_add=True, verbose_name="user's Date and time of membership")),
                ('user_access_date', models.DateTimeField(auto_now=True, verbose_name="user's Last login date")),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user',
                'ordering': ['id'],
            },
        ),
    ]
