# Generated by Django 4.0.3 on 2022-04-04 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.IntegerField(help_text='회원 식별자', primary_key=True, serialize=False)),
                ('user_email', models.CharField(help_text='이메일', max_length=50)),
                ('user_profile', models.CharField(blank=True, help_text='프로필 사진 경로', max_length=512, null=True)),
                ('user_pw', models.CharField(help_text='비밀번호', max_length=100)),
                ('user_name', models.CharField(help_text='회원 이름', max_length=20)),
                ('user_sign_up_date', models.DateTimeField(help_text='회원 가입 일시')),
                ('user_access_date', models.DateTimeField(help_text='최근 접속 일시')),
            ],
            options={
                'ordering': ['user_id'],
            },
        ),
    ]
