# Generated by Django 4.0.3 on 2022-04-04 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='user',
        ),
    ]
