# Generated by Django 3.2.12 on 2022-04-05 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220405_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('dr_id', models.AutoField(primary_key=True, serialize=False, verbose_name="directory's ID")),
                ('dr_name', models.CharField(max_length=10, verbose_name="directory's name")),
                ('dr_pid', models.IntegerField(verbose_name="directory's parent ID")),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'directory',
            },
        ),
    ]
