# Generated by Django 4.0.3 on 2022-04-04 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_users_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.AutoField(help_text='회원 식별자', primary_key=True, serialize=False),
        ),
    ]
