# Generated by Django 3.2.12 on 2022-04-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_directory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='dr_id',
            field=models.AutoField(default='', primary_key=True, serialize=False, verbose_name="directory's ID"),
        ),
    ]
