# Generated by Django 4.0.3 on 2022-04-04 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_users_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={},
        ),
        migrations.AlterModelTable(
            name='users',
            table=None,
        ),
    ]
