# Generated by Django 3.2.12 on 2022-04-05 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_directory_dr_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='dr_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name="directory's ID"),
        ),
        migrations.AlterField(
            model_name='directory',
            name='dr_pid',
            field=models.IntegerField(null=True, verbose_name="directory's parent ID"),
        ),
    ]
