# Generated by Django 4.0.3 on 2022-04-04 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_users_options_alter_users_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['user_id']},
        ),
        migrations.AlterModelTable(
            name='users',
            table='user',
        ),
    ]
