# Generated by Django 3.2.12 on 2022-05-15 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('minute', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('mn_id', models.OneToOneField(db_column='mn_id', default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='keywords', serialize=False, to='minute.minutes')),
                ('keyword1', models.CharField(blank=True, default='', max_length=20, verbose_name="minute's keyword1")),
                ('keyword2', models.CharField(blank=True, default='', max_length=20, verbose_name="minute's keyword2")),
                ('keyword3', models.CharField(blank=True, default='', max_length=20, verbose_name="minute's keyword3")),
            ],
            options={
                'db_table': 'keyword',
            },
        ),
    ]
