# Generated by Django 3.2.12 on 2022-05-17 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('minute', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('kw_id', models.AutoField(primary_key=True, serialize=False)),
                ('keyword1', models.CharField(blank=True, default='', max_length=20, verbose_name="minute's keyword1")),
                ('keyword2', models.CharField(blank=True, default='', max_length=20, verbose_name="minute's keyword2")),
                ('keyword3', models.CharField(blank=True, default='', max_length=20, verbose_name="minute's keyword3")),
                ('mn_id', models.ForeignKey(db_column='mn_id', on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='minute.minutes', unique=True)),
            ],
            options={
                'db_table': 'keyword',
            },
        ),
    ]
